<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header">Add User</h3>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
        <div class="col-lg-12">
            <form role="form" method="post">
                <div class="form-group col-md-6 ">
                    <label for="email">User Email</label>
                    <input class="form-control" placeholder="User Email" name="" required="" value="" type="email">
                </div>
                <div class="form-group col-md-6 ">
                    <label for="name">User Name</label>
                    <input class="form-control" placeholder="Username" name="" required="" value="" type="text">
                </div>
                <div class="form-group col-md-6 ">
                    <label for="name">First Name</label>
                    <input class="form-control" placeholder="First Name" name="" required="" value="" type="text">
                </div>
                <div class="form-group col-md-6 ">
                    <label for="name">Last Name</label>
                    <input class="form-control" placeholder="Last Name" name="" required="" value="" type="text">
                </div>
                <div class="form-group col-md-6 ">
                    <label for="name">Password </label>
                    <input class="form-control" placeholder="Password" name="" required="" value="" type="password">
                </div>
                <div class="form-group col-md-6 ">
                    <label for="name">Repeat Password </label>
                    <input class="form-control" placeholder="Repeat Password" name="" required="" value="" type="password">
                </div>
                <div class="form-group col-md-6 ">
                    <label for="name">User Role</label>
                    <select class="form-control">
                        <option>Administrator</option>
                        <option>Developer</option>
                    </select>
                </div>
                <div class="form-group col-md-6 ">
                    <label for="name">Status</label>
                    <select class="form-control">
                        <option>Active</option>
                        <option>Inactive</option>
                    </select>
                </div>
                <div class="col-md-12 text-right">
                    <button type="submit" class="btn btn-primary">Add User</button>
                </div>
            </form>
        </div>
        </div>
    </div>
</div>