<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header"><?php echo isset($edit) && $edit == 1 ? 'Edit' : 'Add'; ?> User</h3>
            </div>
        </div>
        <?php if(isset($__msg) && !empty($__msg) && is_array($__msg)): ?>
        <p class="alert alert-<?php echo $__msg['type']; ?>"><?php echo $__msg['msg']; ?></p>
        <?php endif; ?>
        <div class="row">
            <div class="col-lg-12">
                <form role="form" method="post">
                    <?php if(isset($edit) && $edit == 1): ?>
                    <input type="hidden" name="user[id]" value="<?php echo $data['id']; ?>" />
                    <?php endif; ?>
                    <div class="form-group col-md-6 ">
                        <label for="email">User Email</label>
                        <input class="form-control" placeholder="User Email" name="user[email]" required="" 
                            value="<?php echo isset($data['email']) ? $data['email'] : ''; ?>" type="email" <?php echo isset($edit) && $edit == 1 ? 'disabled' : NULL; ?>>
                    </div>
                    <div class="form-group col-md-6 ">
                        <label for="name">User Name</label>
                        <input class="form-control" placeholder="Username" name="user[name]" required="" 
                        value="<?php echo isset($data['name']) ? $data['name'] : ''; ?>" type="text" <?php echo isset($edit) && $edit == 1 ? 'disabled' : NULL; ?>>
                    </div>
                    <div class="form-group col-md-6 ">
                        <label for="name">First Name</label>
                        <input class="form-control" placeholder="First Name" name="user[first]" required="" 
                        value="<?php echo isset($data['first']) ? $data['first'] : ''; ?>" type="text">
                    </div>
                    <div class="form-group col-md-6 ">
                        <label for="name">Last Name</label>
                        <input class="form-control" placeholder="Last Name" name="user[last]" required="" 
                        value="<?php echo isset($data['last']) ? $data['last'] : ''; ?>" type="text">
                    </div>
                    <?php if($_SESSION['user']['user_role'] == 1): ?>
                    <div class="form-group col-md-6 ">
                        <label for="name">User Role</label>
                        <select class="form-control" name="user[role]">
                            <option value="2"<?php echo isset($data['role']) && $data['role'] == 2 ? ' selected' : ''; ?>>Developer</option>
                            <option value="1"<?php echo isset($data['role']) && $data['role'] == 1 ? ' selected' : ''; ?>>Administrator</option>
                        </select>
                    </div>
                    <?php endif; ?>
                    <hr />
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
