<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <h3>User Information</h3>
        <br />
        <table class="table no-border">
            <tr>
                <td><strong>Name: </td>
                <td><em><?php  echo ucwords($detail['user_first']); ?> <?php echo ucwords($detail['user_last']); ?></em></td>
            </tr>
            <tr>
                <td><strong>Email: </td>
                <td><em><?php echo $detail['user_email']; ?></em></td>
            </tr>
            <tr>
                <td><strong>Role: </td>
                <td><em><?php echo isset($detail['user_role']) && $detail['user_role'] == 1 ? 'Administrator' : 'Developer' ?></em></td>
            </tr>
            <tr>
                <td><strong>Created Date: </td>
                <td><em><?php echo date('M d, Y H:i', strtotime($detail['user_created'])); ?></em></td>
            </tr>
        </table>

        <div class="panel panel-default">
            <div class="panel-heading">
                List of Servers
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Server Name</th>
                                <th>Root</th>
                                <th>Server IP</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if(empty($server)): ?>
                                <tr>
                                    <td colspan="3" class="text-center">No Server Found</td>
                                </tr>
                            <?php endif; ?>

                            <?php foreach($server as $servers): ?>
                            <tr>
                                <td><?php echo $servers['server_name'] ?></td>
                                <td><?php echo $servers['server_root'] ?></td>
                                <td><?php echo $servers['server_ip'] ?></td>
                            </tr>
                            <?php endforeach; ?>                                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>