<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <h3>User Information</h3>
        <br />
        <?php if(isset($userMsg) && !empty($userMsg)): ?>
        <p class="alert alert-<?php echo $userMsg['type']; ?>"><?php echo $userMsg['msg']; ?></p>
        <?php endif; ?>
        <table class="table no-border">
            <tr>
                <td><strong>Name: </td>
                <td><em><?php  echo ucwords($detail['user_first']); ?> <?php echo ucwords($detail['user_last']); ?></em></td>
            </tr>
            <tr>
                <td><strong>Email: </td>
                <td><em><?php echo $detail['user_email']; ?></em></td>
            </tr>
            <tr>
                <td><strong>Role: </td>
                <td><em><?php echo isset($detail['user_role']) && $detail['user_role'] == 1 ? 'Administrator' : 'Developer' ?></em></td>
            </tr>
            <tr>
                <td><strong>Created Date: </td>
                <td><em><?php echo date('M d, Y H:i', strtotime($detail['user_created'])); ?></em></td>
            </tr>
        </table>

        <div class="panel panel-default">
            <div class="panel-heading">
                List of Servers
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Server Name</th>
                                <th>Server IP</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if(empty($server)): ?>
                                <tr>
                                    <td colspan="3" class="text-center">No Server Found</td>
                                </tr>
                            <?php endif; ?>

                            <?php foreach($server as $v): ?>
                            <tr>
                                <td><?php echo $v['server_name'] ?></td>
                                <td><?php echo $v['server_ip'] ?></td>
                                <td><a href="?remove=<?php echo $v['server_id']; ?>" class="remove"><span class="fa fa-times-circle"></span> remove</a></td>
                            </tr>
                            <?php endforeach; ?>                                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
(function($) {
    $('a.remove').click(function() {
        if(!confirm('Click OK to continue!'))
        {
            return false;
        }

        return true;
    });
}(jQuery))
</script>
