<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <h3>Server Information</h3>
        <br />
        <table class="table no-border">
            <tr>
                <td><strong>Server Name: </td>
                <td><em><?php echo $detail['server_name']; ?></em></td>
            </tr>
            <tr>
                <td><strong>Server Root: </td>
                <td><em><?php echo $detail['server_root']; ?></em></td>
            </tr>
            <tr>
                <td><strong>Server IP: </td>
                <td><em><?php echo $detail['server_ip']; ?></em></td>
            </tr>
            <tr>
                <td><strong>Created Date: </td>
                <td><em><?php echo date('M d, Y H:i', strtotime($detail['server_created'])); ?></em></td>
            </tr>
        </table>

        <div class="panel panel-default">
            <div class="panel-heading">
                List of Users
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Email</th>
                                <th>Username</th>
                                <th>Full Name</th>
                                <th>Role</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if(empty($user)): ?>
                                <tr>
                                    <td colspan="6" class="text-center">No Server Found</td>
                                </tr>
                            <?php endif; ?>

                            <?php foreach($user as $users): ?>
                            <tr>
                                <td><?php echo $users['user_email']; ?></td>
                                <td><?php echo $users['user_name']; ?></td>
                                <td><?php echo ucwords($users['user_first']); ?> <?php echo ucwords($users['user_last']); ?></td>
                                <td><?php echo isset($users['user_role']) && $users['user_role'] == '1' ? 'Administrator' : 'Developer'; ?></td>
                                <td>
                                    <?php if($users['user_active'] == 0): ?>
                                    <span class="label label-warning">Inactive</span>
                                    <?php elseif($users['user_active'] == 1): ?>
                                    <span class="label label-success">Active</span>
                                    <?php else: ?>
                                    <span class="label label-danger">Disabled</span>
                                    <?php endif; ?>
                                </td>
                                <td><a href="/server/detail/<?php echo $users['user_id']; ?>" title="Remove User"><i class="delete fa fa-times-circle"></i></a></td>
                            </tr>
                            <?php endforeach; ?>                                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('.delete').click(function() {
        if(confirm('Click OK to continue!')) {
            return true;
        }

        return false;
    });
</script>