<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header">Add Server</h3>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
        <div class="col-lg-12">
            <form role="form" method="post">
                <div class="form-group col-md-6 ">
                    <label for="email">Server Name</label>
                    <input class="form-control" placeholder="Server Name" name="" required="" value="" type="email">
                </div>
                <div class="form-group col-md-6 ">
                    <label for="name">Root</label>
                    <input class="form-control" placeholder="Root" name="" required="" value="" type="text">
                </div>
                <div class="form-group col-md-6 ">
                    <label for="name">Password </label>
                    <input class="form-control" placeholder="Password" name="" required="" value="" type="password">
                </div>
                <div class="form-group col-md-6 ">
                    <label for="name">Repeat Password </label>
                    <input class="form-control" placeholder="Repeat Password" name="" required="" value="" type="password">
                </div>
                <div class="form-group col-md-6 ">
                    <label for="name">Server IP</label>
                    <input class="form-control" placeholder="Server IP" name="" required="" value="" type="text">
                </div>

                <div class="col-md-12 text-right">
                    <button type="submit" class="btn btn-primary">Add Server</button>
                </div>
            </form>
        </div>
        </div>
    </div>
</div>