<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title text-center">User Access Control</h3>
                </div>
                <div class="panel-body">
                    <form role="form" method="post">
                        <?php if(isset($loginMsg) && !empty($loginMsg) && is_array($loginMsg)): ?>
                        <p class="alert alert-<?php echo $loginMsg['type']; ?>"><?php echo $loginMsg['msg']; ?></p>
                        <?php endif; ?>
                        <fieldset>
                            <div class="form-group">
                                <input class="form-control" placeholder="E-mail or Username" name="login[email]" autofocus="">
                            </div>
                            <div class="form-group">
                                <input class="form-control" placeholder="Password" name="login[password]" value="" type="password">
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input name="remember" value="Remember Me" type="checkbox">Remember Me
                                </label>
                            </div>
                            <!-- Change this to a button or input when using this as a form -->
                            <input type="submit" class="btn btn-lg btn-success btn-block" value="Login" />
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
