<style>
.table td, .table th { font-size: 12px; }
.actions a {
    display: inline-block; 
    font-size: 14px;
    margin: 0 5px;
}

.search-form input[name="q"] {
    border: 1px solid #ddd;
    border-radius: 2px;
    padding: 2px 5px;
}

hr { margin-top: 5px; }
h3 { margin: 0; padding: 0;  }
</style>
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
       <br />
        <div class="row">
            <h3 class="col-xs-6">Server</h3>
            <div class="col-xs-6">
                    <?php echo control()->block('search')
                        ->setPlaceholder('Enter Name or IP')
                    ?>
                    <div class="col-xs-3 text-right">
                        <a href="server/add" type="button" class="btn btn-primary"><i class="fa fa-plus"></i> Add Server</a>
                    </div>
                 </div>
        </div><hr /><br />
        <div class="row">
              <table class="table table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Root</th>
                        <th>IP Address</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if(empty($servers) && isset($_GET['keywords'])): ?>
                    <tr>
                        <td colspan="4" class="text-center">No Servers Found <strong>"<?php echo $_GET['keywords']; ?>"</strong></td>
                    </tr>
                    <?php endif; ?>
                    <?php foreach ($servers as $server): ?>
                    <tr>
                        <td> <a href="/server/detail/<?php echo $server['server_id']; ?>"><?php echo $server['server_name']; ?></a></td>
                        <td><?php echo $server['server_root']; ?></td>
                        <td><?php echo $server['server_ip']; ?></td>
                        <td class="text-center actions">
                            <a href="#" title="Edit Server"><i class="fa fa-pencil-square"></i></a>
                            <a href="?remove=<?php echo $server['server_id']; ?>" class="remove" title="Delete Server"><i class="delete fa fa-times-circle"></i></a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <!-- Pagination -->
        <?php
            $page = isset($_GET['page']) ? $_GET['page']: 1 ;
            echo control()->block('pagination')
            ->setRange($range)
            ->setPage($page)
            ->setTotal($totalServers);
        ?>
    </div>
</div>

<script type="text/javascript">
    $('.remove').click(function() {
        if(confirm('Click OK to continue!')) {
            return true;
        }

        return false;
    });
</script>
