<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header">Servers</h3>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    List of Servers
                    <div class="pull-right">
                        <div class="btn-group">
                            <a href="servers/add" type="button" class="btn btn-outline btn-primary btn-xs">Add Server</a>
                        </div>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Root</th>
                                    <th>IP Address</th>
                                    <th class="text-center">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if(empty($servers)): ?>
                                <tr>
                                    <td colspan="4" class="text-center">No Servers Found</td>
                                </tr>
                                <?php endif; ?>
                                <?php foreach ($servers as $server): ?>
                                <tr>
                                    <td><?php echo $server['server_name']; ?></td>
                                    <td><?php echo $server['server_root']; ?></td>
                                    <td><?php echo $server['server_ip']; ?></td>
                                    <td class="text-center">
                                        <a href="">View Details</a></br>
                                        <a href="/product/edit/1">
                                        <i class="fa fa-pencil-square"></i></a>&nbsp;| 
                                        <a href="/product/delete/1">
                                        <i class="fa fa-times-circle"></i></a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>