<style>
.table td, .table th { font-size: 12px; }
.actions a {
    display: inline-block; 
    font-size: 14px;
    margin: 0 5px;
}

.search-form input[name="q"] {
    border: 1px solid #ddd;
    border-radius: 2px;
    padding: 2px 5px;
}

hr { margin-top: 5px; }
h3 { margin: 0; padding: 0;  }
</style>
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
       <br />
        <div class="row">
            <h3 class="col-xs-6">Server</h3>
            <form class="search-form row col-xs-6 form-inline">
                <div class="col-xs-8">
                        <input type="text" name="q" placeholder="Search here..." class="form-control" />
                        <input type="submit" value="Search" class="btn btn-default" />
                </div>
                <div class="col-xs-4">
                    <a href="server/add" type="button" class="btn btn-primary"><i class="fa fa-plus"></i> Add Server</a>
                </div>
            </form>
        </div><hr /><br />
        <div class="row">
              <table class="table table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Root</th>
                        <th>IP Address</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if(empty($servers)): ?>
                    <tr>
                        <td colspan="4" class="text-center">No Servers Found</td>
                    </tr>
                    <?php endif; ?>
                    <?php foreach ($servers as $server): ?>
                    <tr>
                        <td><?php echo $server['server_name']; ?></td>
                        <td><?php echo $server['server_root']; ?></td>
                        <td><?php echo $server['server_ip']; ?></td>
                        <td class="text-center actions">
                            <a href="/server/detail/<?php echo $server['server_id']; ?>" title="Server Information">
                            <i class="fa fa-info-circle"></i></a>
                            <a href="#" title="Edit Server"><i class="fa fa-pencil-square"></i></a>
                            <a href="#" title="Delete Server"><i class="delete fa fa-times-circle"></i></a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('.delete').click(function() {
        if(confirm('Click OK to continue!')) {
            return true;
        }

        return false;
    });
</script>