<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header">Users</h3>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    List of users
                    <div class="pull-right">
                        <div class="btn-group">
                            <a href="user/add" type="button" class="btn btn-outline btn-primary btn-xs">Add User</a>
                        </div>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                                <tr>
                                    <th>Email</th>
                                    <th>User Name</th>
                                    <th>First Name</th>
                                    <th>Last Name</th>
                                    <th class="text-center">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($users as $user): ?> 
                                <tr>
                                    <td><?php echo $user['user_email']; ?></td>
                                    <td><?php echo $user['user_name']; ?></td>
                                    <td><?php echo $user['user_first']; ?></td>
                                    <td><?php echo $user['user_last']; ?></td>
                                    <td class="text-center">
                                        <a href="/user/detail/<?php echo $user['user_id']; ?>">View Details</a></br>
                                        <a href="/product/edit/1">
                                        <i class="fa fa-pencil-square"></i></a>&nbsp;| 
                                        <a href="/product/delete/1">
                                        <i class="fa fa-times-circle"></i></a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>