<style>
.table td, .table th { font-size: 12px; }
.actions a {
    display: inline-block; 
    font-size: 14px;
    margin: 0 5px;
}

.search-form input[name="q"] {
    border: 1px solid #ddd;
    border-radius: 2px;
    padding: 2px 5px;
}

hr { margin-top: 5px; }
h3 { margin: 0; padding: 0;  }
.dropdown-server { background: #FFF; display: none; border: 1px solid #f1f1f1; }
.dropdown-server a {
    display:block;
    padding: 5px;
}

.dropdown-server a:hover { background:#F0F7F9 }
.server-tags { margin-bottom: 5px; }
.server-tags span { display: inline-block; margin: 0 3px; }

.modal form .control-label { text-align: left; }
.modal form .modal-body { margin: 0 10%; }
.modal form .modal-body a { text-decoration: none; }

</style>

<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <br />
        <div class="row">
            <h3 class="col-xs-6">Users</h3>
            <form class="search-form row col-xs-6 form-inline">
                <div class="col-xs-8">
                        <input type="text" name="q" placeholder="Search here..." class="form-control" />
                        <input type="submit" value="Search" class="btn btn-default" />
                </div>
                <div class="col-xs-4">
                    <a href="user/add" type="button" class="btn btn-primary"><i class="fa fa-plus"></i> Add User</a>
                </div>
            </form>
        </div><hr /><br />
        <div class="row">
              <table class="table table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Email</th>
                        <th>User Name</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Status</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($users as $user): ?> 
                    <tr>
                        <td><?php echo $user['user_email']; ?></td>
                        <td><?php echo $user['user_name']; ?></td>
                        <td><?php echo $user['user_first']; ?></td>
                        <td><?php echo $user['user_last']; ?></td>
                        <td>
                        <?php if($user['user_active'] == 0): ?>
                        <span class="label label-warning">Inactive</span>
                        <?php elseif($user['user_active'] == 1): ?>
                        <span class="label label-success">Active</span>
                        <?php else: ?>
                        <span class="label label-danger">Disabled</span>
                        <?php endif; ?>
                        </td>
                        <td class="text-center actions">
                            <a href="/user/detail/<?php echo $user['user_id']; ?>" title="User Information">
                            <i class="fa fa-info-circle"></i></a>
                            <a href="#" title="Edit User"><i class="fa fa-pencil-square"></i></a>
                            <?php if($user['user_active'] != 2): ?>
                            <a href="?del=<?php echo $user['user_id']; ?>" title="Delete User" class="delete"><i class="fa fa-times-circle"></i></a>

                            <?php endif; ?>
                            <?php if($user['user_active'] == 1): ?>
                            <a href="#" class="userModal" title="Add Server" data-toggle="modal" data-target="#AddServer" data-id="<?php echo $user['user_id']; ?>"><i class="fa fa-plus-circle"></i></a>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="AddServer" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Add User to Server</h4>
            </div>
            <form class="form-horizontal">
                <div class="modal-body">
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Email</label>
                        <div class="col-sm-9">
                            <em><label class="user_email control-label"></label></em>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">User Name</label>
                        <div class="col-sm-9">
                            <em><label class="user_name control-label"></label></em>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">First Name</label>
                        <div class="col-sm-9">
                            <em><label class="user_first control-label"></label></em>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Last Name</label>
                        <div class="col-sm-9">
                            <em><label class="user_last control-label"></label></em>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Servers</label>
                        <div class="col-sm-9">
                            <input type="hidden" name="addToServer[user]" id="add-to-server-user" />
                            <div class="server-tags"></div>
                            <input type="text" class="typeahead form-control" />
                            <div class="dropdown-server"></div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Add to Server</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
$('.typeahead').keyup(function() {
    var val = $('.typeahead').val();
    var x = ''
    $('.server-tags input[type="hidden"]').each(function() {
        x += '&x[]='+$(this).val();
    })
    
    $.get('/users?q='+val+x, function(res) 
    {
        res = eval('('+res+')');
        var html = '';
        for(var i = 0; i < res.length; i++)
        {
            html += '<a href="#" data-val="'+res[i]['server_id']+'">'+res[i]['server_name']+'</a>';
        }

        $('.dropdown-server').html(html);
        $('.dropdown-server').show();
    });
}).blur(function() {
    setTimeout(function() {
        $('.dropdown-server').hide();
    }, 300)
});

$(document).on('click', '.dropdown-server a', function(e) {
    e.preventDefault();
    var html = '<span class="label label-info">'+$(this).html()+'<input type="hidden" name="addToServer[server][]" value="'+$(this).data('val')+'" class="server-ids" /> <a href="#">&times;</a></span>';
    $('.server-tags').append(html);
    $('.typeahead').val('');
});

$(document).on('click', '.server-tags span a', function(e) {
    e.preventDefault();
    $(this).parent().remove();
});

$(function() {
    $('.userModal').on('click',function() {

        var id = $(this).data('id');
        $.ajax({
                type: 'GET',
                url: '/users/'+id,
                dataType: 'json',
                data: {
                    id : id,
                    action : 'getuser'
                },
                success: function(response) {

                    var user          = response,
                        user_email    = user['user_email'],
                        user_name     = user['user_name'];
                        user_first     = user['user_first'];
                        user_last     = user['user_last'];

                    $('label.user_email').text(user_email);
                    $('#add-to-server-user').val(id);
                    $('label.user_name').text(user_name);
                    $('label.user_first').text(user_first);
                    $('label.user_last').text(user_last);
                    $('.server-tags').html('');
                }
        });

    });
    
 });

$('.delete').click(function() {
    if(confirm('Click OK to continue!')) {
        return true;
    }

    return false;
})
</script>
