<link rel="stylesheet" type="text/css" href="/lib/bootstrap-tagsinput/typeaheadjs.css">
<link rel="stylesheet" type="text/css" href="/lib/bootstrap-tagsinput/bootstrap-tagsinput.css">
<script type="text/javascript" src="/lib/bootstrap-tagsinput/typeahead.bundle.min.js"></script>
<script type="text/javascript" src="/lib/bootstrap-tagsinput/bootstrap-tagsinput.min.js"></script>

<style>
.table td, .table th { font-size: 12px; }
.actions a {
    display: inline-block; 
    font-size: 14px;
    margin: 0 5px;
}

.search-form input[name="q"] {
    border: 1px solid #ddd;
    border-radius: 2px;
    padding: 2px 5px;
}

hr { margin-top: 5px; }
h3 { margin: 0; padding: 0;  }
</style>
<!-- Page Content -->

<div id="page-wrapper">
    <div class="container-fluid">
        <br />
        <div class="row">
            <h3 class="col-xs-6">Users</h3>
            <form class="search-form row col-xs-6 form-inline">
                <div class="col-xs-8">
                        <input type="text" name="q" placeholder="Search here..." class="form-control" />
                        <input type="submit" value="Search" class="btn btn-default" />
                </div>
                <div class="col-xs-4">
                    <a href="user/add" type="button" class="btn btn-primary"><i class="fa fa-plus"></i> Add User</a>
                </div>
            </form>
        </div><hr /><br />
        <div class="row">
              <table class="table table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Email</th>
                        <th>User Name</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($users as $user): ?> 
                    <tr>
                        <td><?php echo $user['user_email']; ?></td>
                        <td><?php echo $user['user_name']; ?></td>
                        <td><?php echo $user['user_first']; ?></td>
                        <td><?php echo $user['user_last']; ?></td>
                        <td class="text-center actions">
                            <a href="/user/detail/<?php echo $user['user_id']; ?>" title="User Information">
                            <i class="fa fa-info-circle"></i></a>
                            <a href="#" title="Edit User"><i class="fa fa-pencil-square"></i></a>
                            <a href="#" title="Delete User"><i class="fa fa-times-circle"></i></a>
                            <a href="#" class="userModal" title="Add Server" data-toggle="modal" data-target="#AddServer" data-user="<?php echo $user['user_name']; ?>"><i class="fa fa-plus-circle"></i></a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="AddServer" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Add User to Server</h4>
            </div>
            <form class="form-horizontal">
                <div class="modal-body">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Name</label>
                        <div class="col-sm-10">
                            <input type="text" class="name form-control"  placeholder="Name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Servers</label>
                        <div class="col-sm-10">
                            <input type="text" class="typeahead form-control" name="server"/>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>  
$(function() {

    /* category tags and autocomplete */
    this.tagInput = $('input.typeahead');
    var categories = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        remote: '/users?q=%QUERY'});

    categories.initialize();
    this.tagInput.tagsinput({
        trimValue: true,
        typeaheadjs: {
            name: 'server',
            displayKey: 'server_name',
            valueKey: 'server_name',
            source: categories.ttAdapter()
        }
    });

    $('.userModal').on('click',function() {
        var username = $(this).data('user');
        $('input.name').val(username);
    });
    
 });
</script>


