<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
	    <div class="row">
	        <div class="col-md-4 col-md-offset-4">
	            <div class="login-panel panel panel-default">
	                <div class="panel-heading">
	                    <h3 class="panel-title text-center">User Access Control</h3>
	                </div>
	                <div class="panel-body">
	                    <form role="form" method="post">
	                       
	                        <fieldset>
	                            <div class="form-group">
	                                <input class="form-control" placeholder="E-mail or Username" name="login[email]" autofocus="">
	                            </div>
	                            <div class="form-group">
	                                <input class="form-control" placeholder="Password" name="login[password]" value="" type="password">
	                            </div>
	                            <div class="form-group">
	                                <input class="form-control" placeholder="Repeat Password" name="login[password_repeat]" value="" type="password">
	                            </div>
	                            <!-- Change this to a button or input when using this as a form -->
	                            <input type="submit" class="btn btn-lg btn-success btn-block" value="Login" />
	                        </fieldset>
	                    </form>
	                </div>
	            </div>
	        </div>
	    </div>
    </div>
</div>