<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">User Access Control</a>
    </div>
    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown pull-right">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <?php echo ucwords($_SESSION['user']['user_first']); ?> <?php echo ucwords($_SESSION['user']['user_last']); ?>&nbsp;&nbsp;<i class="fa fa-caret-down"></i>
            </a>
        <ul class="dropdown-menu dropdown-user">
            <li><a href="/"><i class="fa fa-user fa-fw"></i> Profile</a></li>
            <li class="divider"></li>
            <li><a href="/setting"><i class="fa fa-user fa-fw"></i> Setting</a></li>
            <li class="divider"></li>
            <li><a href="/?logout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
            </li>
        </ul>
        </li>
    </ul>
    <?php if(isset($_SESSION['user']['user_role']) && $_SESSION['user']['user_role'] == 1): ?>
    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <a href="/users"><i class="fa fa-user fa-fw"></i> Users</a>
                </li>
                <li>
                    <a href="/servers"><i class="fa fa-server fa-fw"></i> Servers</a>
                </li>
            </ul>
        </div>
    </div>
    <?php endif; ?>
</nav>
