<!DOCTYPE html>
<html class="<?php print $class; ?>">
    
<head>
    <title><?php print $title; ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    
    <?php if(isset($meta) && is_array($meta)): ?>
    <?php foreach($meta as $name => $content): ?>
    <meta name="<?php print $name; ?>" content="<?php print $content; ?>" />
    <?php endforeach; ?>
    <?php endif; ?>

    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/lib/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="/lib/sb-admin/css/metisMenu.min.css" />
    <link rel="stylesheet" href="/lib/sb-admin/css/sb-admin-2.css" />
    <link rel="stylesheet" href="/styles/global.css" />
    <link rel="stylesheet" href="/styles/style.css" />
    <link rel="stylesheet" href="/styles/media.css" />
    <script type="text/javascript" src="/lib/jquery.js"></script>
</head>

<body>
    <div class="page">
        <div class="head"><?php echo isset($_SESSION['user']) && !empty($_SESSION['user']) && is_array($_SESSION['user']) ? $head : ''; ?></div>
        <div class="body"><?php echo $body; ?></div>
        <div class="foot"><?php echo isset($_SESSION['user']) && !empty($_SESSION['user']) && is_array($_SESSION['user']) ? $foot : ''; ?></div>
        <script type="text/javascript" src="/lib/bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/lib/sb-admin/js/metisMenu.min.js"></script>
        <script type="text/javascript" src="/lib/sb-admin/js/metisMenu.min.js"></script>
        <script type="text/javascript" src="/scripts/script.js"></script>
    </div>
</body>
</html>
